---
- name: Automate ubuntu
  hosts: localhost
  tasks:
    - name: Install ZSH
      ansible.builtin.command: apt install zsh
      become: true
      changed_when: false

    - name: Install oh-my-zsh
      ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      become: true
      changed_when: false

    - name: Oh-my-zsh extenstions
      ansible.builtin.command: code --install-extension {{ items }}
      with_items:
        - git
        - zsh-syntax-highlighting
        - zsh-autosuggestions
        - docker
      changed_when: output.rc != 0

    - name: Check for Python
      ansible.builtin.raw: test -e /usr/bin/python
      changed_when: false
      register: check_python

    - name: Install Python
      ansible.builtin.command: apt -y update && apt install -y python-minimal
      when: check_python.rc != 0
      become: true
      changed_when: false
